### PR TITLE
Make localstorage independent of Flutter

### PR DESCRIPTION
**Pull request by comigor**
Following https://github.com/lesnitsky/flutter_localstorage/pull/12, this PR make it possible to use `localstorage` completely without Flutter (eg. Dart CLI apps).

⚠️ There's a breaking change, substituting `onError` from `ValueNotifier` to a simple `Stream`.

### CODE REVIEW

**Review by lesnitsky — CHANGES_REQUESTED** [review]
Since this is a breaking change please also bump a major version in pubspec.yaml
I'm also wondering what's your use-case for localstorage as independent plugin? Are you using in it on dart server?

**Comment by comigor** [comment]
@lesnitsky Yes, actually I do use it for multiplatform (desktop + mobile) flutter apps, and it can probably be adapted to work with flutter_web in the future!

**Comment by comigor** [comment]
@lesnitsky I've upgraded the version and added to CHANGELOG

**Comment by lesnitsky** [comment]
adoption for flutter_web has nothing to do with this changes :) as per PR title, intention is to make it possible to use this package outside of flutter ecosystem, so I had a second thought and realized that I don't want to maintain any other potential dart env. Also path related stuff in current implementation isn't correct but rather a temporary "workaround", afaik actual implementation for macos, linux, windows is coming to `path_provider` package itself.

**Comment by comigor** [comment]
I understand. In fact I didn't know `path_provider` was working on it directly, so good to know!
Thanks for your time anyway!

**Pull request closed without merging**
