### PR TITLE
fix noSuchMethodError in _flush

### PR DESCRIPTION
**Pull request by KorionCN**
for this issue: https://github.com/lesnitsky/flutter_localstorage/issues/14

### CODE REVIEW

**Review by oakromulo — APPROVED** [review]
this should definitely get merged

**Comment by oakromulo** [comment]
@KorionCN: I merged your changes into PR https://github.com/lesnitsky/flutter_localstorage/pull/17 if you don't mind

**Comment by KorionCN** [comment]
ok, just do it

**Comment by lesnitsky** [comment]
Closing since going to merge #15

**Pull request closed without merging**
