### PR TITLE
Add null safety

### LINKED ISSUE #62: "FileSystemException: lock failed" on subsequent setItem()
Version: 3.0.6, Platform: Windows

<details>
    <summary><code>.setItem()</code> method fails on 2nd call</summary>

```
FileSystemException: lock failed, path = 'C:\Users\tcd93\Documents/test' (OS Error: The process cannot access the file because another process has locked a portion of the file.
, errno = 33)
dart:io                                           _RandomAccessFile.lock
DirUtils.flush
package:localstorage/…/directory/io.dart:47
LocalStorage._flush
package:localstorage/localstorage.dart:102
LocalStorage.setItem
package:localstorage/localstorage.dart:85
===== asynchronous gap ===========================
```

</details>

Code:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:localstorage/localstorage.dart';

void main() {
  LocalStorage storage;
  setUpAll(() => storage = new LocalStorage('test'));
  tearDownAll(() => storage.dispose());
  test('LocalStorage', () async {
    await storage.ready;
    await storage.setItem('test_key', '{"1": "one", "2": "two", "3": "three"}');
    await storage.setItem('test_key', '{"4": "four"}'); // fails
  });
}
```

Looks like it is caused by a missing `_file.unlock` here:
https://github.com/lesnitsky/flutter_localstorage/blob/6f4447ea65c8479032ed04c36bef5340bdf67f53/lib/src/directory/io.dart#L44-L52

**Not reproducible on real device / emulator**

### LINKED ISSUE #65: Support for dart 3.0 null-safety

### LINKED ISSUE #67: Data not typed after upgrade
Hi

I migrated my Flutter application to use package version 3.0.6 + 9 instead of 3.0.0 + 3, but after this update my app started having problems reading data incorrectly.
I save some json files on the disk and when I read this data it is not typed and I get this error:
The type 'MyModel' is not a subtype of type 'Map<String, dynamic>'.
I also reset the device , so wtitting file with new package, but the issue is still the same

I have now restored the package with this version
localstorage: "<3.0.1" and my app is working fine

### LINKED ISSUE #68: migrate to nullSafety
with flutter v2.0.0, Dart's sound null-safety is stable now, so for safe migrate projects to it, flutter recommended wait for migration of all project dependencies to null-safety, I have project depended on this awesome flutter plugin, please migrate it 🙏🏻

### PR DESCRIPTION
**Pull request by tcd93**
fix #62 
fix #65
fix #68

### CODE REVIEW

**Comment by ThijSlim** [comment]
@lesnitsky review and merge this please :)

**Review by rauleburro — COMMENTED** [review]
I thing it was ok

**Comment by ThijSlim** [comment]
I have reached out to @lesnitsky by e-mail. I hope he responds soon :)

**Comment by tcd93** [comment]
You can use my repo as replacement while waiting for this, like so:
```yaml
dependencies:
  flutter_localstorage:
    git:
      url: git://github.com/flutter/plugin1.git
```

**Comment by ducnm2359** [comment]
> You can use my repo as replacement while waiting for this, like so:
> 
> ```yaml
> dependencies:
>   flutter_localstorage:
>     git:
>       url: git://github.com/flutter/plugin1.git
> ```

Please publish this one :D

**Comment by lesnitsky** [comment]
just published this version
sorry for taking so long to reply

**Pull request merged**
