### PR TITLE
release/v2.0.1

### PR DESCRIPTION
**Pull request by oakromulo**
- update dependencies [2019-10-18]
- address issue https://github.com/lesnitsky/flutter_localstorage/issues/26

### CODE REVIEW

**Comment by lesnitsky** [comment]
fixed by 876b8e6c8c0890cd96d20b35e7bec0ff51ccd8eb

**Comment by oakromulo** [comment]
dependencies remain outdated, see:
https://github.com/lesnitsky/flutter_localstorage/commit/14f210f35e7bb0bd211fdda5008faa9a650e96b3

**Comment by lesnitsky** [comment]
86e27ac9e431c29feeaf10397564d2f728e51eda

**Comment by oakromulo** [comment]
still @ 1.1.0, it should have been 1.4.0

**Comment by lesnitsky** [comment]
I'm stupid 🤦‍♂️
876614ccd5fa78394afb009428f802c163ae2110

**Comment by oakromulo** [comment]
дзякуй!

**Comment by lesnitsky** [comment]
De nada! 😅

**Pull request closed without merging**
